### ISSUE TITLE
How to run it from cron?

### ISSUE THREAD

**Issue by 7starsone** [pdufault/mysqlfragfinder#14]
Hello,
If I try to run it from cron I get:
```
tput: No value for $TERM and no -T specified
```
how to... ? thanks and Happy New Year

**Comment by 7starsone** [comment]
the issue is with ***tput***

is there an easy way instead of editing the code?

**Comment by pdufault** [comment]
The script could test if it's in an interactive shell via this I think:
```
if [[ $- =~ i ]];
```
